#ifndef _KDI_SDK_ERRORCODE_H_
#define _KDI_SDK_ERRORCODE_H_
enum ErrorCode{
	//ERROR_EM_BEGIN = 80000,
	//ERROR_EM_END = 89999,

	EVT_EMI_SUCCESS=70000,

	//失败
	EV_EMI_ERROR_DEV_ADD_EXIST_ERROR = 80000,			//添加已经存在的设备
	EV_EMI_ERROR_DEV_DEL_NOTEXIST_ERROR,				//删除不存在的设备	
	EV_EMI_ERROR_DEV_UPDATE_NOTEXIST_ERROR,				//更改不存在的设备
	EV_EMI_ERROR_DEV_CONTROL_NOTEXIST_ERROR,			//控制不存在的设备
	EV_EMI_ERROR_DEV_DLLWRAPPER_NOTEXIST_ERROR,         //设备动态库管理不存在
	EV_EMI_ERROR_DEV_DLLWRAPPER_NULL_ERROR,             //设备动态库管理指针为空
	EV_EMI_ERROR_DEV_HANDLE_NULL_ERROR,                 //设备句柄为空


	EV_EMI_ERROR_COM_ISUSE = 81000,							//串口被占用
	EV_EMI_ERROR_COM_NOT_PRESENT,							//串口不可用
	EV_EMI_ERROR_COM_MODULE_NOT_INIT,						//串口模块未初始化
	EV_EMI_ERROR_COM_MODULE_OPEN_ERROR,						//串口模块打开失败
	EV_EMI_ERROR_COM_MODULE_INIT_ERROR,						//串口模块初始化失败
	EV_EMI_ERROR_COM_MODULE_RELEASE_ERROR,					//串口模块释放失败
	EV_EMI_ERROR_COM_SEND_ERROR,							//发送COM数据失败
	EV_EMI_ERROR_COM_OVERFLOW,								//达到COM连接上限
	EV_EMI_ERROR_COM_CONFIG_ERROR,							//串口参数配置错误

	EV_EMI_ERROR_TCP_MODULE_NOT_INIT = 81010,			//TCP模块未初始化
	EV_EMI_ERROR_TCP_MODULE_INIT_ERROR,					//TCP模块初始化失败
	EV_EMI_ERROR_TCP_MODULE_OPEN_ERROR,					//TCP模块打开失败
	EV_EMI_ERROR_TCP_MODULE_RELEASE_ERROR,				//TCP模块释放失败 
	EV_EMI_ERROR_TCP_SEND_ERROR,						//发送TCP数据失败
	EV_EMI_ERROR_TCP_OVERFLOW,							//达到TCP连接上限

	EV_EMI_ERROR_UDP_MODULE_NOT_INIT = 81020,			//UDP模块未初始化
	EV_EMI_ERROR_UDP_MODULE_INIT_ERROR,					//UDP模块初始化失败
	EV_EMI_ERROR_UDP_MODULE_OPEN_ERROR,					//UDP模块打开失败
	EV_EMI_ERROR_UDP_MODULE_RELEASE_ERROR,				//UDP模块释放失败
	EV_EMI_ERROR_UDP_SEND_ERROR,						//发送UDP数据失败
	EV_EMI_ERROR_UDP_OVERFLOW,							//达到UDP连接上限
	EV_EMI_ERROR_UDP_SESSION_UNAVALIBLE,                // Udp创建失败

	EV_EMI_ERROR_TCP_SERVER_MODULE_NOT_INIT = 81030,			//TCP 服务模块未初始化
	EV_EMI_ERROR_TCP_SERVER_MODULE_INIT_ERROR,					//TCP 服务模块初始化失败
	EV_EMI_ERROR_TCP_SERVER_MODULE_OPEN_ERROR,					//TCP 服务模块打开失败
	EV_EMI_ERROR_TCP_SERVER_MODULE_RELEASE_ERROR,				//TCP 服务模块释放失败

	EV_EMI_ERROR_DEV_NOT_INIT= 81100,					//设备未初始化
	EV_EMI_ERROR_DEV_INIT_ERROR= 81101,					//设备初始化失败
	EV_EMI_ERROR_DEV_CFG_ERROR,							//设备配置错误
	EV_EMI_ERROR_DEV_CONFIG_OVERFLOW,					//达到设备配置上限	
	EV_EMI_ERROR_DEV_OFFLINE,							//设备不在线
	EV_EMI_ERROR_DEV_NOT_FIND,							//设备不存在
	EV_EMI_ERROR_DEV_NOT_SUPORT,						//不支持的设备
	EV_EMI_ERROR_NOT_SUPORT_PROTOCOL,					//不支持的协议类型
	EV_EMI_ERROR_NOT_SUPORT_CONNECT,					//不支持的连接方式
	EV_EMI_ERROR_DEV_CNT_ADDRESS_EXIST,					//同一连接方式的相同控制器地址的设备已经存在
	EV_EMI_ERROR_DEV_CONNECT_FAIL,                      // 连接失败
	EV_EMI_ERROR_DEV_CLOSE_FAIL,						//关闭连接失败 
	EM_EMI_ERROR_START_TASK_FAIL,						//启动任务失败
	EM_EMI_ERROR_DLL_LOAD_FAIL,							//加载动态库失败

	EV_EMI_ERROR_DEV_CONTROL,							//操作设备失败
	EV_EMI_ERROR_CONTROL_NOT_SUPORT,					//不支持的操作
	EV_EMI_ERROR_CONTROL_DEV_FAILED,					//控制设备失败

	EV_EMI_ERROR_DEV_NO_CFG_ERROR = 81200,				//配置设备号错误

	EV_EMI_ERROR_DSS_NOT_USE = 82000,					//dss 未启用
	EV_EMI_ERROR_DSS_NOT_CONNECTED,						//dss 未连接

	EV_EMI_ERROR_MEMORY_NEW,							//内存申请错误
	EV_EMI_ERROR_DB_OPER,								//操作数据库失败
	EV_EMI_ERROR_INVALID_PARAM,							//无效的参数

	EV_EMI_ERROR_PUINT_HOST_NOT_REG,					//智能服务器未注册
	EV_EMI_ERROR_PUINT_HOST_CONNECT_FAILED,				//智能服务器连接失败
	EV_EMI_ERROR_PUINT_HOST_GET_POINT_LIST,				//获取智能服务点列表失败
	EV_EMI_ERROR_PUINT_NOT_EXIST,						//该平台不存在智能点

	EV_EMI_ERROR_BC_FILE_NOT_EXIST,						//不存在广播文件
	EV_EMI_ERROR_BC_POINT_NOT_EXIST,					//不存在广播点


	EV_EMI_ERROR_CONFIG_TIMEOUT = 83008,						  //设备配置超时
	EV_EMI_ERROR_SMS_RUN_ERROR = 83009,							//SMS启动失败
	EV_EMI_ERROR_SMS_CONTROL_SEND_ERROR,                //SMS发送错误
	EV_EMI_ERROR_SMS_REGESTER_ERROR,                    //SMS注册失败
	EV_EMI_ERROR_SMS_DLL_NOTLOAD,                       //SMS DLL未找到
	EV_EMI_ERROR_SMS_CONTROL_SMS_INIT,                  // 短信猫启动失败
	EV_EMI_ERROR_SMS_CONTROL_WRITE_COM,                 // 写串口失败				
	EV_EMI_ERROR_SMS_CONTROL_READ_COM,                  // 读串口失败			
	EV_EMI_ERROR_SMS_CONTROL_CLEAR_COMM,                // 清串口失败					
	EV_EMI_ERROR_SMS_CONTROL_NO_VALID_GPRS_MODEM,       // 检测GSM MODEM设备失败		
	EV_EMI_ERROR_SMS_CONTROL_NO_SIM_CARD,               // 检测SIM卡失败				
	EV_EMI_ERROR_SMS_CONTROL_NO_SINGAL,                 // 检测SIM信号失败	80040
	EV_EMI_ERROR_SMS_SNED_SMS_FAIL,						          // 发送短信失败
	EV_EMI_ERROR_SMS_DLL_NOT_FIND,						          //SMS DLL找不到
	EV_EMI_ERROR_SMS_DLL_INIT,							            //SMS DLL初始化失败
	EV_EMI_ERROR_SMS_DLL_RELEASE,						            //SMS DLL释放失败
	EV_EMI_ERROR_SMS_DLL_REGESTER,						          //SMS 注册回调失败
	EV_EMI_ERROR_SMS_CLOSE,								              //SMS 关闭失败
	EV_EMI_ERROR_SMS_NOT_INIT,							            //SMS未初始化

	EV_EMI_ERROR_DEV_PROTOCOL_NOT_INIT,					//设备模块未初始化 
	EV_EMI_ERROR_DEV_PROTOCOL_INIT,						//初始化设备模块失败UDP80130 
	EV_EMI_ERROR_DEV_PROTOCOL_RELEASE,					//释放设备模块失败
	EV_EMI_ERROR_DEV_PROTOCOL_NOT_OPEN,					//设备模块未打开
	EV_EMI_ERROR_DEV_PROTOCOL_CONNECT,					//连接设备模块失败
	EV_EMI_ERROR_DEV_PROTOCOL_DISCONNECT,				//断开设备模块失败
	EV_EMI_ERROR_DEV_PROTOCOL_START_DATA_DETECT,		//开始设备模块数据检测失败
	EV_EMI_ERROR_DEV_PROTOCOL_STOP_DATA_DETECT = 83034,			//停止设备模块数据检测失败

	EV_EMI_ERROR_SPEAK_SERIAL_NOT_INIT = 84000,					//对讲序列号没有设置
	EV_EMI_ERROR_WEIGENG_DOOR_NOT_REGISTER = 84001,				//微耕门禁控件未注册
	EV_EMI_ERROR_BOSCHHK_ALARM_CREATE_LISTENPORT_ERROR = 84002, //博世告警主机海康模块创建监听端口失败

	EV_EMI_ERROR_UNKNOWN = 89999,						//未知错误
};
#endif